### ISSUE TITLE
Doesn't seem to work on personal substacks.

### ISSUE THREAD

**Issue by zyansheep** [timf34/Substack2Markdown#12]
Trying to scrape my newly-created substack gives this error. Looking at the xml it downloads on line 103 doesn't seem to reveal anything wrong :thinking:. One thing that might be different is that I'm using a personal substack (as opposed to a publication?) which seems to have a [different layout](https://zyansheep.substack.com). Seems to work just fine on astralcodexten.

```
❯ python substack_scraper.py --url https://zyansheep.substack.com --directory posts
Traceback (most recent call last):
  File "/home/zyansheep/Repos/substack_scraper/substack_scraper.py", line 492, in <module>
    main()
  File "/home/zyansheep/Repos/substack_scraper/substack_scraper.py", line 474, in main
    scraper = SubstackScraper(args.url, md_save_dir=args.directory, html_save_dir=args.html_directory)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zyansheep/Repos/substack_scraper/substack_scraper.py", line 341, in __init__
    super().__init__(base_substack_url, md_save_dir, html_save_dir)
  File "/home/zyansheep/Repos/substack_scraper/substack_scraper.py", line 91, in __init__
    self.post_urls: List[str] = self.get_all_post_urls()
                                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zyansheep/Repos/substack_scraper/substack_scraper.py", line 97, in get_all_post_urls
    urls = self.fetch_urls_from_sitemap()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zyansheep/Repos/substack_scraper/substack_scraper.py", line 113, in fetch_urls_from_sitemap
    root = ET.fromstring(response.content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/current-system/sw/lib/python3.12/xml/etree/ElementTree.py", line 1335, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 103, column 33
```

Any thoughts?

**Comment by timf34** [comment]
Hey @zyansheep,

I haven't stepped through your example with the code, but it doesn't seem like your substack has a sitemap or rss feed at your URL (I tried appending sitemap.xml and feed.xml but no luck) which I'm guessing is the root of the problem. We need the sitemap or rss feed to get the links to the blog posts for a substack.  

If you feed the script a link directly to your essay at the appropriate place where the URLs are processed it should be able to convert that if you want.
Thanks,
Tim
